name: shoplocalto
description: wem2017.github.io
version: 1.0.6+12
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.1.2
  firebase_analytics: ^9.1.4
  firebase_messaging: ^11.2.12
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  bloc: ^4.0.0
  emoji_picker_flutter: ^1.1.2
  get: ^4.6.1
  flutter_bloc: ^4.0.0
  dio: ^4.0.4
  flutter_swiper: ^1.1.6
  readmore: ^2.1.0
  shimmer: ^1.1.1
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^0.5.4
  image_picker: ^0.8.4+6
  photo_view: ^0.9.2
  intro_views_flutter: ^2.8.1
  intro_slider: ^2.3.3
  rflutter_alert: ^1.1.0
  connectivity_plus: ^2.3.0
  carousel_slider: ^2.3.1
  flutter_typeahead: ^3.2.4
  url_launcher: ^6.0.18
  flutter_signin_button: ^1.1.0
  http: ^0.13.4
  flutter_switch: ^0.3.2
  double_back_to_close: ^2.0.0
  flutter_secure_storage: ^3.3.5
  geolocator: ^8.1.1
  geocoder: ^0.2.1
  geocoding: ^2.0.2
  font_awesome_flutter: ^8.11.0
  syncfusion_flutter_sliders: ^19.4.54
  firebase_auth: ^3.3.13
  firebase_core: ^1.14.0
  google_sign_in: ^5.2.4
#  flutter_facebook_login: ^3.0.0
#  flutter_login_facebook: ^1.2.1
#  flutter_facebook_auth: ^4.1.2
  permission_handler: ^8.3.0
#  flutter_facebook_login: ^3.0.0
  cloud_firestore: ^3.1.12
#  facebook_sdk: ^0.0.7
#  flutter_facebook_sdk: ^1.0.0
#  facebook_app_events: ^0.9.0
  path_provider: ^2.0.8
#  flutter_facebook_auth: ^4.3.4+2
#  agora_rtc_engine: ^5.0.1
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.3.2+1
  json_serializable: ^6.1.4

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/data/
    - assets/images/
    - assets/locale/
    - assets/socialicons/
    - assets/pictures/
    - assets/videos/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-BlackItalic.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-BoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway-ExtraLightItalic.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-LightItalic.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-MediumItalic.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
        - asset: assets/fonts/Raleway-ThinItalic.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Black.ttf
        - asset: assets/fonts/Merriweather-BlackItalic.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather-BoldItalic.ttf
        - asset: assets/fonts/Merriweather-Italic.ttf
        - asset: assets/fonts/Merriweather-Light.ttf
        - asset: assets/fonts/Merriweather-LightItalic.ttf
        - asset: assets/fonts/Merriweather-Regular.ttf
  uses-material-design: true